"use client";

import { useState, useRef, useEffect } from "react";
import { Download, Copy, FileText, Printer, Check } from "lucide-react";

interface ExportMenuProps {
  content: string;
  title?: string;
}

export default function ExportMenu({ content, title = "InvoiceForge AI Output" }: ExportMenuProps) {
  const [open, setOpen] = useState(false);
  const [copied, setCopied] = useState(false);
  const menuRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const handler = (e: MouseEvent) => {
      if (menuRef.current && !menuRef.current.contains(e.target as Node)) {
        setOpen(false);
      }
    };
    if (open) document.addEventListener("mousedown", handler);
    return () => document.removeEventListener("mousedown", handler);
  }, [open]);

  const copyMarkdown = async () => {
    await navigator.clipboard.writeText(content);
    setCopied(true);
    setTimeout(() => {
      setCopied(false);
      setOpen(false);
    }, 1500);
  };

  const downloadTxt = () => {
    const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${title.replace(/\s+/g, "-").toLowerCase()}-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    setOpen(false);
  };

  const printPdf = () => {
    const printWindow = window.open("", "_blank");
    if (!printWindow) return;
    printWindow.document.write(`<!DOCTYPE html>
<html>
<head>
  <title>${title}</title>
  <style>
    @media print { @page { margin: 1in; } }
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; font-size: 14px; line-height: 1.7; color: #18181b; max-width: 800px; margin: 0 auto; padding: 2rem; }
    h1 { font-size: 1.5rem; margin-bottom: 0.25rem; }
    .meta { font-size: 0.8rem; color: #71717a; margin-bottom: 2rem; border-bottom: 1px solid #e4e4e7; padding-bottom: 1rem; }
    pre { white-space: pre-wrap; word-wrap: break-word; font-family: inherit; }
  </style>
</head>
<body>
  <h1>${title}</h1>
  <div class="meta">Generated by InvoiceForge AI &middot; ${new Date().toLocaleDateString()}</div>
  <pre>${content.replace(/</g, "&lt;").replace(/>/g, "&gt;")}</pre>
</body>
</html>`);
    printWindow.document.close();
    printWindow.onload = () => printWindow.print();
    setOpen(false);
  };

  if (!content) return null;

  return (
    <div ref={menuRef} className="relative">
      <button
        onClick={() => setOpen(!open)}
        className="p-1.5 rounded-lg transition-all duration-200 hover:bg-accent/10 focus:outline-none focus:ring-2 focus:ring-accent/30"
        title="Export"
      >
        <Download className="w-4 h-4 text-textMuted hover:text-accent transition-colors" />
      </button>

      {open && (
        <div className="absolute right-0 top-full mt-2 w-52 rounded-xl border border-border py-1.5 z-50 shadow-xl bg-surface/95 backdrop-blur-xl">
          <button
            onClick={copyMarkdown}
            className="w-full flex items-center gap-3 px-4 py-2.5 text-sm text-textMuted hover:text-text hover:bg-surfaceHover transition-colors"
          >
            {copied ? <Check className="w-4 h-4 text-accent" /> : <Copy className="w-4 h-4" />}
            {copied ? "Copied!" : "Copy Markdown"}
          </button>
          <button
            onClick={downloadTxt}
            className="w-full flex items-center gap-3 px-4 py-2.5 text-sm text-textMuted hover:text-text hover:bg-surfaceHover transition-colors"
          >
            <FileText className="w-4 h-4" />
            Download .txt
          </button>
          <button
            onClick={printPdf}
            className="w-full flex items-center gap-3 px-4 py-2.5 text-sm text-textMuted hover:text-text hover:bg-surfaceHover transition-colors"
          >
            <Printer className="w-4 h-4" />
            Print / PDF
          </button>
        </div>
      )}
    </div>
  );
}
